import type { NumerologyCoreNumber, NumerologyProfile } from "./types";

export const NUMEROLOGY_PROFILES: Record<NumerologyCoreNumber, NumerologyProfile> = {
  1: {
    number: 1,
    title: "Người khởi xướng",
    strengths: ["Độc lập", "Chủ động", "Có tinh thần dẫn dắt"],
    weaknesses: ["Dễ nóng vội", "Khó nhờ hỗ trợ", "Có xu hướng tự áp lực"],
    growthDirections: ["Rèn kiên nhẫn", "Lắng nghe phản hồi", "Chọn mục tiêu rõ ràng"],
    love: "Cần không gian riêng nhưng nên học cách chia sẻ cảm xúc đều đặn hơn.",
    work: "Phù hợp vai trò mở đường, xây sản phẩm, quản lý dự án hoặc kinh doanh.",
  },
  2: {
    number: 2,
    title: "Người kết nối",
    strengths: ["Tinh tế", "Biết hợp tác", "Giỏi lắng nghe"],
    weaknesses: ["Dễ do dự", "Nhạy cảm với phê bình", "Ngại xung đột"],
    growthDirections: ["Đặt ranh giới", "Ra quyết định dứt khoát", "Tin vào quan sát của mình"],
    love: "Đề cao sự an toàn cảm xúc, hợp với mối quan hệ có đối thoại nhẹ nhàng.",
    work: "Phù hợp tư vấn, chăm sóc khách hàng, nhân sự, điều phối hoặc cộng tác sáng tạo.",
  },
  3: {
    number: 3,
    title: "Người biểu đạt",
    strengths: ["Sáng tạo", "Hoạt ngôn", "Truyền cảm hứng"],
    weaknesses: ["Dễ phân tán", "Ngại kỷ luật dài hạn", "Cảm xúc thay đổi nhanh"],
    growthDirections: ["Xây thói quen nhỏ", "Hoàn thiện trước khi mở rộng", "Ghi lại ý tưởng"],
    love: "Cần sự vui vẻ, tương tác và cảm giác được ghi nhận trong tình cảm.",
    work: "Phù hợp nội dung, marketing, nghệ thuật, đào tạo, truyền thông hoặc sản phẩm.",
  },
  4: {
    number: 4,
    title: "Người xây nền",
    strengths: ["Kỷ luật", "Thực tế", "Bền bỉ"],
    weaknesses: ["Dễ cứng nhắc", "Sợ thay đổi", "Quá chú trọng chi tiết"],
    growthDirections: ["Linh hoạt hơn", "Chừa khoảng nghỉ", "Thử nghiệm có kiểm soát"],
    love: "Thể hiện tình cảm qua sự ổn định và trách nhiệm, nên nói rõ nhu cầu hơn.",
    work: "Phù hợp vận hành, kỹ thuật, tài chính, quy trình, quản lý chất lượng.",
  },
  5: {
    number: 5,
    title: "Người trải nghiệm",
    strengths: ["Linh hoạt", "Tò mò", "Thích nghi nhanh"],
    weaknesses: ["Dễ chán", "Khó duy trì cam kết", "Có thể quyết định bốc đồng"],
    growthDirections: ["Đặt giới hạn", "Theo dõi tiến độ", "Chọn tự do có cấu trúc"],
    love: "Cần sự mới mẻ và tôn trọng tự do, nhưng nên rõ ràng về cam kết.",
    work: "Phù hợp bán hàng, truyền thông, du lịch, phát triển thị trường, sản phẩm số.",
  },
  6: {
    number: 6,
    title: "Người nuôi dưỡng",
    strengths: ["Trách nhiệm", "Ấm áp", "Biết chăm sóc"],
    weaknesses: ["Dễ ôm việc", "Hay lo thay người khác", "Cầu toàn trong gia đình"],
    growthDirections: ["Chia sẻ trách nhiệm", "Chăm sóc bản thân", "Không kiểm soát quá mức"],
    love: "Đề cao sự gắn bó và chăm sóc, cần tránh hy sinh quá nhiều.",
    work: "Phù hợp giáo dục, thiết kế dịch vụ, y tế chăm sóc, nhân sự, cộng đồng.",
  },
  7: {
    number: 7,
    title: "Người quan sát",
    strengths: ["Sâu sắc", "Phân tích tốt", "Thích tìm hiểu bản chất"],
    weaknesses: ["Dễ khép kín", "Hoài nghi", "Khó chia sẻ suy nghĩ"],
    growthDirections: ["Mở lòng có chọn lọc", "Chuyển tri thức thành hành động", "Giữ nhịp xã hội"],
    love: "Cần kết nối trí tuệ và sự tin cậy, không hợp với áp lực quá dồn dập.",
    work: "Phù hợp nghiên cứu, dữ liệu, chiến lược, công nghệ, phân tích chuyên sâu.",
  },
  8: {
    number: 8,
    title: "Người kiến tạo thành tựu",
    strengths: ["Tham vọng", "Quản trị tốt", "Có tư duy kết quả"],
    weaknesses: ["Dễ căng thẳng", "Có thể kiểm soát mạnh", "Đặt nặng thành công"],
    growthDirections: ["Cân bằng quyền lực", "Quản lý năng lượng", "Đo thành công đa chiều"],
    love: "Cần học cách hiện diện cảm xúc thay vì chỉ giải quyết vấn đề.",
    work: "Phù hợp quản lý, kinh doanh, tài chính, vận hành, chiến lược tăng trưởng.",
  },
  9: {
    number: 9,
    title: "Người phụng sự",
    strengths: ["Bao dung", "Lý tưởng", "Có chiều sâu nhân văn"],
    weaknesses: ["Dễ ôm cảm xúc", "Khó buông chuyện cũ", "Kỳ vọng cao"],
    growthDirections: ["Đặt ranh giới", "Hành động thực tế", "Chọn việc tạo tác động rõ"],
    love: "Yêu sâu và rộng lượng, nên tránh cứu rỗi hoặc gánh cảm xúc thay người khác.",
    work: "Phù hợp giáo dục, xã hội, nghệ thuật, chữa lành, truyền thông vì cộng đồng.",
  },
  11: {
    number: 11,
    title: "Người truyền cảm hứng",
    strengths: ["Trực giác mạnh", "Nhạy cảm", "Có khả năng truyền tải ý tưởng"],
    weaknesses: ["Dễ quá tải", "Lo âu", "Khó ổn định cảm xúc"],
    growthDirections: ["Giữ nền tảng sinh hoạt", "Diễn đạt trực giác thành kế hoạch", "Chọn môi trường lành mạnh"],
    love: "Cần sự tinh tế và thấu hiểu, đồng thời cần ranh giới cảm xúc rõ.",
    work: "Phù hợp sáng tạo, cố vấn, truyền thông, giáo dục, công việc truyền cảm hứng.",
  },
  22: {
    number: 22,
    title: "Người kiến tạo lớn",
    strengths: ["Tầm nhìn", "Tổ chức", "Biến ý tưởng lớn thành hệ thống"],
    weaknesses: ["Áp lực cao", "Sợ thất bại", "Dễ gánh quá nhiều"],
    growthDirections: ["Chia nhỏ kế hoạch", "Xây đội ngũ", "Đo tiến bộ theo giai đoạn"],
    love: "Cần người đồng hành tôn trọng mục tiêu lớn nhưng vẫn nhắc về cân bằng.",
    work: "Phù hợp xây tổ chức, sản phẩm quy mô, vận hành, kiến trúc hệ thống, đầu tư dài hạn.",
  },
  33: {
    number: 33,
    title: "Người nâng đỡ",
    strengths: ["Tận tâm", "Chữa lành", "Có sức ảnh hưởng cảm xúc"],
    weaknesses: ["Dễ hy sinh", "Quá trách nhiệm", "Khó nói không"],
    growthDirections: ["Chăm sóc bản thân trước", "Chọn phạm vi hỗ trợ", "Không đồng nhất giá trị với sự hy sinh"],
    love: "Rất giàu chăm sóc, nên giữ quan hệ cân bằng hai chiều.",
    work: "Phù hợp giáo dục, cố vấn, chăm sóc, cộng đồng, nghệ thuật mang tính nâng đỡ.",
  },
};
