import type { ReportRenderModel } from "@/lib/report-engine/report-schema";
import type { ResultModel } from "@/lib/result/result-types";

export const FORBIDDEN_REPORT_TERMS = [
  "chắc chắn",
  "sẽ",
  "định mệnh",
  "100%",
  "tuyệt đối",
  "đại họa",
  "phá sản",
  "ly hôn chắc chắn",
  "AI diễn giải",
  "AI phân tích",
  "generated by AI",
] as const;

export interface ForbiddenTermMatch {
  field: string;
  term: string;
  value: string;
}

export interface ContentQualityResult {
  forbiddenWordsFound: ForbiddenTermMatch[];
  isPass: boolean;
}

export interface ResultQualityIssue {
  field: string;
  message: string;
}

export interface ResultQualityResult extends ContentQualityResult {
  issues: ResultQualityIssue[];
}

function normalizeText(value: string) {
  return value.toLowerCase();
}

export function checkTextQuality(
  value: string,
  field = "text",
): ContentQualityResult {
  const normalizedValue = normalizeText(value);
  const forbiddenWordsFound = FORBIDDEN_REPORT_TERMS.filter((term) =>
    normalizedValue.includes(term.toLowerCase()),
  ).map((term) => ({
    field,
    term,
    value,
  }));

  return {
    forbiddenWordsFound,
    isPass: forbiddenWordsFound.length === 0,
  };
}

function collectReportText(report: ReportRenderModel) {
  return [
    ["overview.title", report.overview.title],
    ["overview.description", report.overview.description],
    ["keyInsight.title", report.keyInsight.title],
    ["keyInsight.body", report.keyInsight.body],
    ["interpretation.title", report.interpretation.title],
    ["interpretation.body", report.interpretation.body],
    ["strengths.title", report.strengths.title],
    ["strengths.description", report.strengths.description],
    ["cautions.title", report.cautions.title],
    ["cautions.description", report.cautions.description],
    ["career.title", report.career.title],
    ["career.description", report.career.description],
    ["finance.title", report.finance.title],
    ["finance.description", report.finance.description],
    ["relationship.title", report.relationship.title],
    ["relationship.description", report.relationship.description],
    ["health.title", report.health.title],
    ["health.description", report.health.description],
    ["recommendations.title", report.recommendations.title],
    ["recommendations.description", report.recommendations.description],
    ["disclaimer", report.disclaimer],
    ...report.strengths.items.map((item, index) => [
      `strengths.items.${index}`,
      item,
    ]),
    ...report.cautions.items.map((item, index) => [
      `cautions.items.${index}`,
      item,
    ]),
    ...report.career.items.map((item, index) => [`career.items.${index}`, item]),
    ...report.finance.items.map((item, index) => [
      `finance.items.${index}`,
      item,
    ]),
    ...report.relationship.items.map((item, index) => [
      `relationship.items.${index}`,
      item,
    ]),
    ...report.health.items.map((item, index) => [`health.items.${index}`, item]),
    ...report.recommendations.items.map((item, index) => [
      `recommendations.items.${index}`,
      item,
    ]),
    ...report.why.flatMap((item, index) =>
      item.reason.map((reason, reasonIndex) => [
        `why.${index}.reason.${reasonIndex}`,
        reason,
      ]),
    ),
    ...report.sources.map((source, index) => [
      `sources.${index}.explanation`,
      source.explanation,
    ]),
  ] as Array<[string, string]>;
}

export function checkReportContentQuality(
  report: ReportRenderModel,
): ContentQualityResult {
  const forbiddenWordsFound = collectReportText(report).flatMap(([field, value]) =>
    checkTextQuality(value, field).forbiddenWordsFound,
  );

  return {
    forbiddenWordsFound,
    isPass: forbiddenWordsFound.length === 0,
  };
}

function collectResultText(result: ResultModel) {
  return [
    ["title", result.title],
    ["summary", result.summary],
    ["keyInsight", result.keyInsight],
    ["shareText", result.shareText],
    ...result.strengths.map((item, index) => [`strengths.${index}`, item]),
    ...result.cautions.map((item, index) => [`cautions.${index}`, item]),
    ...result.advice.map((item, index) => [`advice.${index}`, item]),
    ...result.why.flatMap((item, index) => [
      [`why.${index}.knowledge`, item.knowledge],
      [`why.${index}.rule`, item.rule],
      [`why.${index}.reason`, item.reason],
      [`why.${index}.conclusion`, item.conclusion],
    ]),
    ...result.sources.map((item, index) => [
      `sources.${index}`,
      `${item.label} ${item.description}`,
    ]),
  ] as Array<[string, string]>;
}

export function checkResultQuality(result: ResultModel): ResultQualityResult {
  const issues: ResultQualityIssue[] = [];

  if (result.summary.length < 80) {
    issues.push({ field: "summary", message: "Summary quá ngắn." });
  }

  if (result.why.length === 0) {
    issues.push({ field: "why", message: "Thiếu phần vì sao." });
  }

  if (result.sources.length === 0) {
    issues.push({ field: "sources", message: "Thiếu nguồn phân tích." });
  }

  if (result.advice.length === 0) {
    issues.push({ field: "advice", message: "Thiếu gợi ý áp dụng." });
  }

  const forbiddenWordsFound = collectResultText(result).flatMap(([field, value]) =>
    checkTextQuality(value, field).forbiddenWordsFound,
  );

  return {
    forbiddenWordsFound,
    isPass: issues.length === 0 && forbiddenWordsFound.length === 0,
    issues,
  };
}
